config/routes.rb
Rails.application.routes.draw do

  resources :videos
  root 'homepage#index'

  Rails.application.routes.draw do
    get "/about" => "about#show"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/video.rb
class Video < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
    render template: "about/index"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to videos_url, notice: 'Video was successfully added.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :iframe)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/about/index.html.erb
<div class="container-fluid about">

  <!-- First Row -->
  <div class="row justify-content-md-center">

    <!-- 10 column Main part of the Page -->
    <div class="col-lg-10">
        <h1>About Us</h1>
    </div>

  </div>

  <!-- Second Row -->
  <div class="row justify-content-md-center">
    <div class="col-lg-10">

      <div class="row justify-content-md-center">
        <!-- Phil -->
        <div class="col-lg-4 profile-container">
          <div class="profile">
            <h3>Phil</h3>
          </div>
        </div>

        <!-- Dave -->
        <div class="col-lg-4 profile-container">
          <div class="profile">
            <h3>Dave</h3>
          </div>
        </div>

        <!-- Daniel -->
        <div class="col-lg-4 profile-container">
          <div class="profile">
          <h3>Daniel</h3>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Third Row -->
  <div class="row justify-content-md-center">

    <!-- 10 column bottom -->
    <div class="col-lg-10">
        <h1>What We Do</h1>
    </div>

  </div>

</div>

app/views/homepage/index.html.erb
<div class="homepage">

  <div class="container-fluid">

    <!-- First Row, Intro, Video, Instagram -->
    <div class="row justify-content-md-center">

      <!-- 7 column Main part of the Home Page -->
      <div class="col-lg-7">
          <h1>Jaywalk the World</h1>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.
            Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
            It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
          </p>

          <div class="embed-responsive embed-responsive-16by9 landing-video" >
            <iframe class="embed-responsive-item" width="720" height="405" src="https://www.youtube.com/embed/vkMMVkZMz7c?rel=0" frameborder="0" allowfullscreen></iframe>
          </div>

          <!-- More Videos  -->
          <div class="more-videos row">
            <div class="video-link col centered">Video</div>
            <div class="video-link col centered">Video</div>
            <div class="video-link col centered">Video</div>
          </div>

      </div>

      <!-- 3 Column Instagram Feed -->
      <div class="col-lg-3 ">
        <h3 class="centered">Instagram Feed</h3>
        <div id="instafeed" class="row no-gutters"></div>
      </div>

    </div>

    <!-- Second Row -->
    <div class="row justify-content-md-center">
      <div class="col-lg-10">
        <h2>Places We have JayWalked</h2>

        <figure class="landing-map img-fluid" >
          <%= render :file => "homepage/map" %>
        </figure>
      </div>

    </div>

  </div>

</div>

app/views/homepage/map.html.erb
<script src="https://www.amcharts.com/lib/3/ammap.js" type="text/javascript"></script>
<script src="https://www.amcharts.com/lib/3/maps/js/worldHigh.js" type="text/javascript"></script>
<script src="https://www.amcharts.com/lib/3/themes/dark.js" type="text/javascript"></script>
<div id="mapdiv" style="width: 1000px; height: 450px;"></div>
<!-- <div style="width: 1000px; font-size: 70%; padding: 5px 0; text-align: center; background-color: #173E80; margin-top: 1px; color: #B4B4B7;"><a href="https://www.amcharts.com/visited_countries/" style="color: #B4B4B7;">Create your own visited countries map</a> or check out the <a href="https://www.amcharts.com/" style="color: #B4B4B7;">JavaScript Charts</a>.</div> -->
<script type="text/javascript">
var map = AmCharts.makeChart("mapdiv",{
type: "map",
theme: "dark",
projection: "mercator",
panEventsEnabled : true,
backgroundColor : "#173E80",
backgroundAlpha : 1,
zoomControl: {
zoomControlEnabled : true
},
dataProvider : {
map : "worldHigh",
getAreasFromMap : true,
areas :
[
	{
		"id": "AT",
		"showAsSelected": true
	},
	{
		"id": "BE",
		"showAsSelected": true
	},
	{
		"id": "HR",
		"showAsSelected": true
	},
	{
		"id": "CZ",
		"showAsSelected": true
	},
	{
		"id": "DK",
		"showAsSelected": true
	},
	{
		"id": "FR",
		"showAsSelected": true
	},
	{
		"id": "DE",
		"showAsSelected": true
	},
	{
		"id": "GR",
		"showAsSelected": true
	},
	{
		"id": "HU",
		"showAsSelected": true
	},
	{
		"id": "IS",
		"showAsSelected": true
	},
	{
		"id": "IE",
		"showAsSelected": true
	},
	{
		"id": "IT",
		"showAsSelected": true
	},
	{
		"id": "NL",
		"showAsSelected": true
	},
	{
		"id": "NO",
		"showAsSelected": true
	},
	{
		"id": "PT",
		"showAsSelected": true
	},
	{
		"id": "ES",
		"showAsSelected": true
	},
	{
		"id": "CH",
		"showAsSelected": true
	},
	{
		"id": "GB",
		"showAsSelected": true
	},
	{
		"id": "BS",
		"showAsSelected": true
	},
	{
		"id": "BM",
		"showAsSelected": true
	},
	{
		"id": "CA",
		"showAsSelected": true
	},
	{
		"id": "GT",
		"showAsSelected": true
	},
	{
		"id": "HN",
		"showAsSelected": true
	},
	{
		"id": "US",
		"showAsSelected": true
	},
	{
		"id": "ID",
		"showAsSelected": true
	},
	{
		"id": "JP",
		"showAsSelected": true
	},
	{
		"id": "TW",
		"showAsSelected": true
	},
	{
		"id": "TH",
		"showAsSelected": true
	},
	{
		"id": "VN",
		"showAsSelected": true
	},
	{
		"id": "NZ",
		"showAsSelected": true
	},
  {
		"id": "MT",
		"showAsSelected": true
	}

]
},
areasSettings : {
autoZoom : true,
color : "#B4B4B7",
colorSolid : "#84E884",
selectedColor : "#84E884",
outlineColor : "#6B6B6B",
rollOverColor : "#F5F59D",
rollOverOutlineColor : "#000000"
}
});
</script>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-6 text-center text-md-left">
        <h3>Follow Us</h3>
          <!-- Social icons designed by Pixel Buddha from Flaticon https://www.flaticon.com/packs/logotypes-->
          <div class="social-icons">
            <!-- Instagram -->
            <a target="_blank" title="follow us on instagram" href="https://www.instagram.com/jaywalktheworld/">
              <%= image_tag("icons/instagram.png", alt: "Follow us on Instagram") %>
            </a>

            <!-- Facebook -->
            <a target="_blank" title="follow us on facebook" href="https://www.facebook.com/jaywalktheworld/">
              <%= image_tag("icons/facebook.png", alt: "Follow us on Facebook")%>
            </a>

            <!-- Youtube -->
            <a target="_blank" title="follow us on youtube" href="https://www.youtube.com/channel/UCcGPKlO-xoexKtwQNbuxfMQ">
              <%= image_tag("icons/youtube.png", alt: "Follow us on Youtube")%>
            </a>

            <!-- Twitter -->
            <a target="_blank" title="follow us on twitter" href="https://twitter.com/jaywalktheworld">
              <%= image_tag("icons/twitter.png", alt: "Follow us on Twitter")%>
            </a>

          </div>
      </div>
      <div class="col">
        <!-- 1 of 3 -->
      </div>
      <div class="col">
        <!-- 1 of 3 -->
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="/">JayWalk the World</a>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item <%= 'active' if current_page?(root_path) %>">
        <%= link_to "Home", root_path(), class: "nav-link" %>
      </li>
      <li class="nav-item <%= 'active' if current_page?(videos_path) %>">
        <%= link_to "Videos", videos_path(), class: "nav-link" %>
      </li>
      <li class="nav-item <%= 'active' if current_page?(about_path) %>">
        <%= link_to "About", about_path(), class: "nav-link" %>
      </li>

      <!-- <li class="nav-item">
        <a class="nav-link" href="#">Blog</a>
      </li> -->

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JayWalkTheWorld</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Limelight|Dosis" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/header' %>
      <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/videos/_form.html.erb
<%= form_for(video) do |f| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :iframe %>
    <%= f.text_area :iframe, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :type %>
    <br>
    <div class="content-type">
    <%= f.radio_button :type, 'Youtube', :checked => true, class: "form-check-input" %>
    <%= f.label :type, 'Youtube', :value => 'Youtube' %>
    <br>
    <%= f.radio_button :type, 'Facebook', class: "form-check-input" %>
    <%= f.label :type, 'Facebook', :value => 'Facebook' %>
  </div>
  </div>

  <div>
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<div class="container-fluid about">

  <!-- First Row -->
  <div class="row justify-content-md-center">

    <!-- 7 column Main part of the Page -->
    <div class="col-lg-11">
        <!-- <p id="notice"><%= notice %></p> -->
        <h1>Videos</h1>
        <%= link_to 'New Video', new_video_path, class: 'btn btn-primary' %>
        <br>

        <div class="row justify-content-md-center text-center">
        <% @videos.each do |video| %>
          <div class="col-lg-4">
            <div class="col-lg-12 embed-responsive embed-responsive-16by9 video-feed">

              <div class="vid-iframe"><%= raw video.iframe %></div>

              <%= video.title %>

            </div>
          </div>

            <!-- <%= link_to 'Show', video %>
            <%= link_to 'Edit', edit_video_path(video) %>
            <%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %> -->

        <% end %>
        </div>

    </div>

  </div>

  <!-- Second Row -->
  <div class="row justify-content-md-center">
    <div class="col-lg-10">
    </div>
  </div>

</div>

app/views/videos/new.html.erb
<div class="container-fluid videos">

  <!-- First Row -->
  <div class="row justify-content-md-center">

    <!-- 10 column Main part of the Page -->
    <div class="col-lg-10">
      <%= link_to 'Back', videos_path %>
      <h1>New Video</h1>

      <%= render 'form', video: @video %>

    </div>

  </div>
</div>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @video.title %>
</p>

<p>
  <strong>Iframe:</strong>
  <%= @video.iframe %>
</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>